"""Hill Mixture MMM - Bayesian Marketing Mix Modeling with Mixture of Hill Curves."""

from .benchmark import (
    BenchmarkCaseResult,
    BenchmarkRunConfig,
    BenchmarkThresholds,
    ComparisonThresholds,
    assert_case_passes,
    assert_comparison_passes,
    case_summary,
    compare_case_results,
    evaluate_case_diagnostic_status,
    evaluate_diagnostic_summary,
    plot_case_comparison,
    plot_observed_vs_predictive,
    plot_response_curves,
    resolve_case_artifact_dir,
    resolve_comparison_artifact_dir,
    run_prepared_synthetic_benchmark_case,
    run_real_benchmark_case,
    run_synthetic_benchmark_case,
    save_case_artifacts,
)
from .data import (
    DGP_CONFIGS,
    ControlledKSpacingConfig,
    DGPConfig,
    compute_prior_config,
    generate_controlled_k_spacing_data,
    generate_data,
)
from .inference import (
    compute_convergence_diagnostics,
    compute_label_invariant_diagnostics,
    compute_loo,
    compute_predictions,
    compute_waic,
    run_inference,
)
from .metrics import (
    compute_across_seed_component_stability,
    compute_component_curve_tv_separation,
    compute_component_distance_matrix,
    compute_component_set_alignment,
    compute_delta_loo,
    compute_effective_k,
    compute_inverse_simpson_effective_count,
    compute_latent_recovery,
    compute_leinster_cobbold_effective_count,
    compute_parameter_recovery,
    compute_permutation_invariant_component_recovery,
    compute_predictive_metrics,
    compute_rao_quadratic_entropy_equivalent_count,
    compute_shannon_effective_count,
    compute_similarity_adjusted_effective_count,
    compute_soft_component_count,
    compute_total_variation_distance,
    summarize_component_posterior,
    summarize_true_components,
)
from .models import (
    model_hill_mixture_hierarchical_reparam,
    model_single_hill,
)
from .transforms import adstock_geometric, hill, hill_matrix

__version__ = "0.1.0"

__all__ = [
    "DGPConfig",
    "ControlledKSpacingConfig",
    "DGP_CONFIGS",
    "generate_data",
    "generate_controlled_k_spacing_data",
    "compute_prior_config",
    "BenchmarkCaseResult",
    "BenchmarkRunConfig",
    "BenchmarkThresholds",
    "ComparisonThresholds",
    "run_synthetic_benchmark_case",
    "run_prepared_synthetic_benchmark_case",
    "run_real_benchmark_case",
    "assert_case_passes",
    "assert_comparison_passes",
    "compare_case_results",
    "case_summary",
    "evaluate_case_diagnostic_status",
    "evaluate_diagnostic_summary",
    "plot_observed_vs_predictive",
    "plot_response_curves",
    "plot_case_comparison",
    "resolve_case_artifact_dir",
    "resolve_comparison_artifact_dir",
    "save_case_artifacts",
    "run_inference",
    "compute_convergence_diagnostics",
    "compute_label_invariant_diagnostics",
    "compute_loo",
    "compute_predictions",
    "compute_predictive_metrics",
    "compute_waic",
    "compute_delta_loo",
    "compute_effective_k",
    "compute_total_variation_distance",
    "compute_latent_recovery",
    "compute_component_curve_tv_separation",
    "compute_component_distance_matrix",
    "compute_shannon_effective_count",
    "compute_inverse_simpson_effective_count",
    "compute_rao_quadratic_entropy_equivalent_count",
    "compute_leinster_cobbold_effective_count",
    "compute_similarity_adjusted_effective_count",
    "compute_soft_component_count",
    "compute_component_set_alignment",
    "compute_permutation_invariant_component_recovery",
    "compute_across_seed_component_stability",
    "compute_parameter_recovery",
    "summarize_true_components",
    "summarize_component_posterior",
    "model_single_hill",
    "model_hill_mixture_hierarchical_reparam",
    "adstock_geometric",
    "hill",
    "hill_matrix",
]
